#name of workflow
name: Deploy Tracker App

#when the workflow will be triggered
on:
  push:
    branches:
      - main

#start list of jobs in pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      #install dependencies
      #'npm ci' works the same as 'npm install' but is preferred command for CI/CD
      - name: Install dependencies
        run: |
          npm ci

      - name: Check Secrets and Build the App
        env:
          REACT_APP_ENV: prod
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG }}
        run: |
          if [ -z "$REACT_APP_FIREBASE_CONFIG" ]; then
            echo "::error::Secret 'Firebase Config' is missing or empty!"
            exit 1
          else
            echo "Secrets found! Building the app..."
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
