# name of workflow
name: Deploy Tracker App

# when the workflow will be triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod
      config:
        description: 'Firebase Config'
        required: false
        type: string

# environment variables on top level, available to all jobs
env:
  REACT_APP_ENV: ${{ github.event.inputs.environment || 'prod' }}
  REACT_APP_FIREBASE_CONFIG: ${{  github.event.inputs.config || secrets.REACT_APP_FIREBASE_CONFIG }}

# permissions
permissions:
  contents: write

# list of jobs in pipeline
jobs:
  build-and-deploy:
    # slim image boot a bit faster (not for heavy builds, docker not supported)
    runs-on: ubuntu-slim

    steps:
      - name: Check Secrets
        run: |
          if [ -z "$REACT_APP_FIREBASE_CONFIG" ]; then
            echo "Failed to load Secrets"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          # this will cache the node_modules folder
          # cache: 'npm'
          # cache-dependency-path: '**/package.json'

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.REACT_APP_ENV }}-build-${{ hashFiles('**/package-lock.json') }}

      # Install dependencies if not updated
      # 'npm ci' is same as 'npm install' but preferred command for CI/CD
      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci --loglevel error

      - name: Build the App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
